### ISSUE TITLE
cfdiengine: remove hardcoding regading metodos de pago from cfdi

### ISSUE THREAD

**Issue by pianodaemon** [pianodaemon/erp#44]
https://github.com/pianodaemon/erp/blob/1d5b045497b93a74c3fb879848bdeec85bbab560/DOS/cfdiengine/docmaker/builders/facxml.py#L479 

Currently Gerald is altering this value every time he lifts the phone for the rrm users

**Comment by ombdev** [comment]
el postgres pedido_edit() recibe un param que se guarda/actualiza en poc_pedidos.cfdi_metodo_id.

**Comment by ombdev** [comment]
7701dc8e99ee467235415557ba4f29ba3e1db39a (branch undoing_wrong)
