### ISSUE TITLE
sales-api: clave producto servicio

### ISSUE THREAD

**Issue by pianodaemon** [pianodaemon/erp#45]
En kathion la clave producto servicio era tomada de la familia de producto.

El enfoque que se usara de ahora en adelante para todas las empresas es :

La clave producto servicio esta asociada directamente al producto.

En la versión de producción de rrm, esto ya funciona así, https://github.com/pianodaemon/erp/blob/1d5b045497b93a74c3fb879848bdeec85bbab560/DOS/cfdiengine/docmaker/builders/facxml.py#L151

 Por lo que hay que portar la correción a esta erp unico

**Comment by ombdev** [comment]
Parece que no se usa la tabla cfdi_claveprodserv3 ni el campo inv_prod_tipos.cfdi_prodserv_id
